services:
  backend:
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_DEBUG: "True"
    volumes:
      - ./backend:/app

  celery_worker:
    command: celery -A config worker -l debug --concurrency=1
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
      - ./backend:/app

  celery_beat:
    command: celery -A config beat -l debug --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.dev
    volumes:
      - ./backend:/app

  frontend:
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
